# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\ncatalog.v1\"\x1f\n\x11GetProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\"&\n\x17\x42\x61tchGetProductsRequest\x12\x0b\n\x03ids\x18\x01 \x03(\t\"5\n\x15SearchProductsRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"m\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x05 \x01(\t\x12\x11\n\timage_url\x18\x06 \x01(\t\"A\n\x18\x42\x61tchGetProductsResponse\x12%\n\x08products\x18\x01 \x03(\x0b\x32\x13.catalog.v1.Product\"?\n\x16SearchProductsResponse\x12%\n\x08products\x18\x01 \x03(\x0b\x32\x13.catalog.v1.Product2\x8a\x02\n\x0e\x43\x61talogService\x12@\n\nGetProduct\x12\x1d.catalog.v1.GetProductRequest\x1a\x13.catalog.v1.Product\x12]\n\x10\x42\x61tchGetProducts\x12#.catalog.v1.BatchGetProductsRequest\x1a$.catalog.v1.BatchGetProductsResponse\x12W\n\x0eSearchProducts\x12!.catalog.v1.SearchProductsRequest\x1a\".catalog.v1.SearchProductsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPRODUCTREQUEST']._serialized_start=29
  _globals['_GETPRODUCTREQUEST']._serialized_end=60
  _globals['_BATCHGETPRODUCTSREQUEST']._serialized_start=62
  _globals['_BATCHGETPRODUCTSREQUEST']._serialized_end=100
  _globals['_SEARCHPRODUCTSREQUEST']._serialized_start=102
  _globals['_SEARCHPRODUCTSREQUEST']._serialized_end=155
  _globals['_PRODUCT']._serialized_start=157
  _globals['_PRODUCT']._serialized_end=266
  _globals['_BATCHGETPRODUCTSRESPONSE']._serialized_start=268
  _globals['_BATCHGETPRODUCTSRESPONSE']._serialized_end=333
  _globals['_SEARCHPRODUCTSRESPONSE']._serialized_start=335
  _globals['_SEARCHPRODUCTSRESPONSE']._serialized_end=398
  _globals['_CATALOGSERVICE']._serialized_start=401
  _globals['_CATALOGSERVICE']._serialized_end=667
# @@protoc_insertion_point(module_scope)
